spring:
  application:
    name: rentflow-api-springboot
  profiles:
    default: dev  # Perfil por defecto al arrancar si no se especifica otro

# Bloqueo de Swagger por defecto por seguridad productiva
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false